name: Packer Build

on:
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: test
        uses: ./
        with:
          command: echo-n $SECRET | base64 --decode > test.pem
          working_directory: ./packer

      - name: test1
        uses: ./
        with:
          command: cat test.pem
          working_directory: ./packer

      - name: Packer Validate
        uses: ./
        with:
          command: packer validate -syntax-only build.pkr.hcl
          working_directory: ./packer
      