name: Packer Build

on:
  workflow_dispatch:

jobs:
  packer:
    runs-on: self-hosted
    name: packer
    
    steps:
      - uses: actions/checkout@v2

      - name: Packer Validate
        uses: ./
        with:
          command: packer validate -syntax-only build.pkr.hcl
          working_directory: ./packer
      