name: Packer Build

on:
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Packer Validate
        uses: ./
        with:
          command: packer validate -syntax-only build.pkr.hcl
          working_directory: ./packer
      